export const POPULATE_PAGE_INDEX = 'POPULATE_PAGE_INDEX';
export const POPULATE_PAGE_HELLO = 'POPULATE_PAGE_HELLO';
export const POPULATE_PAGE_HELLO_SUCCESS = 'POPULATE_PAGE_HELLO_SUCCESS';
export const POPULATE_PAGE_HELLO_ERROR = 'POPULATE_PAGE_HELLO_ERROR';
